module.exports = {
  hello: 'hello，welcome to MIOT Extension development !',
  selfDefineScene: 'custom scene',
  timeSetting: 'time setting',
  countDownTime: 'countdown time',
  lighting: "Lighting",
  switchOff: "Off",
  switchOn: "On",
  swing: "Swing",
  dimming: 'Dimming',
  temperature: 'Temperature',
  waterfall: "Waterfall bath",
  hotSpring: "Hot spring bath",
  baby: "Baby bath",
  ion: "Ionic dry hair",
  AI: "AI air purifier",
  defecation: "Going to the toilet",
  smartWashing: "Wash up",
  sterilize: "Antibacterial dehumidification",
  standbyMode: "Standby",
  manufacturer: "Manufacturer",
  model: "Model",
  deviceID: "Device ID",
  FirmwareVersion: "Firmware version",
  deviceInfo: "Device Information",
  baseInfo: "Basic information"
};
