module.exports = {
  closed: 'Closed',
  aqi: 'AQI',
  swTemp: 'Out Temp',
  snTemp: 'In Temp',
  swHumi: 'Out Hum',
  snHumi: 'In Hum',
  workMode: 'Mode',
  auto: 'Auto',
  shouD: 'Manual', // 原键名可能是拼音错误，建议改为 `manual` 更规范，但按原键名翻译
  timer: 'Timer',
  sleep: 'Sleep',
  operatingMode: 'Operating Mode',
  nxh: 'Recirculation',
  jiaShi: 'Humidify',
  chuShi: 'Deh',
  tongFeng: 'Vent',
  nwxh: 'Mixed',
  xinFeng: 'Fresh Air',
  xinFengCS: 'FA Deh',
  dang: 'Level', // 表示设备档位时常用 "Gear" 或 "Level"
  songFJ: 'Supply',
  paiFJ: 'Exhaust',
  lvWSY: 'Filter Life',
  set: 'Settings', // 作为名词“设置”常用复数形式
  flz: 'Ions',
  dn: 'Heat',
  zwd: 'UV', // UV 紫外线灯缩写
  jD: 'Static',
  kF: 'Valve Open',
  jS: 'Humidifier',
  ptf: 'Bypass',
  ff: 'Damper',
  chuC: 'Dust',
  huaS: 'Defrost',
  cancel: 'Cancel',
  confirm: 'Confirm',
  historyData: 'History',
  lock: 'Child Lock',
  powerOff: 'Off',
  powerOn: 'On',
  week: 'Week',
  day: 'Day',
  chart1Title: 'In/Out Temp',
  chart1Title1: 'In Temp',
  chart1Title2: 'Out Temp',
  chart2Title: 'In/Out Hum',
  chart2Title1: 'In Hum',
  chart2Title2: 'Out Hum',
  chart3Title: 'CO₂',
  chart4Title: 'PM2.5',
  chart5Title: 'VOC',
  chart6Title: 'CH₂O',
  filterTipTitle: 'Total filter usage time',
  filterTip1: 'Total use: xx h',
  filterTip2: 'Run time: xx h',
  filterTitle: 'Filter'
};