module.exports = {
    hello: 'hello，welcome to MIOT Extension development !',
    selfDefineScene: 'custom scene',
    timeSetting: 'time setting',
    countDownTime: 'countdown time',

    homeTitle: 'Home',
    timer: 'Timer',
    timer3Hours: '3 hours',
    timer6Hours: '6 hours',
    timerContinuous: 'Continuous',
    standby: 'Standby',
    heating: 'Heating',
    ventilation: 'Ventilation',
    coolDry: 'Cool dry',
    hotDry: 'Hot dry',
    gear: 'Fan speed',
    windDirection: 'Wind direction',
    windType: 'Wind type',
    strong: 'Strong',
    weak: 'Weak',
    auto: 'Auto',
    fixed: 'Fixed',
    fixed90: 'Fixed 90°',
    diffuse: 'Diffuse',
    focus: 'Focused',
    coolLight: 'Cool light',
    modeTitle: 'Mode',
    standbyRunning: 'In standby',
    endAfter: 'Ends after',
    cancel: 'Cancel',
    confirm: 'Confirm',
    saveTip: 'Tap to save'
};
