module.exports = {
    hello: '你好，欢迎加入 MIOT 扩展程序开发!',
    selfDefineScene: '自定义场景',
    timeSetting: '时间设置',
    countDownTime: '倒计时',

    homeTitle: '首页',
    timer: '定时',
    timer3Hours: '3小时',
    timer6Hours: '6小时',
    timerContinuous: '连续',
    standby: '待机',
    heating: '制热',
    ventilation: '换气',
    coolDry: '凉干燥',
    hotDry: '热干燥',
    gear: '档位',
    windDirection: '风向',
    windType: '风种',
    strong: '强',
    weak: '弱',
    auto: '自动',
    fixed: '固定',
    fixed90: '固定90°',
    diffuse: '扩散',
    focus: '集中',
    coolLight: '冷光灯',
    modeTitle: '模式',
    standbyRunning: '待机中',
    endAfter: '后结束',
    cancel: '取消',
    confirm: '确定',
    saveTip: '点我保存'
};
