module.exports = {
  'snTemp': 'Indoor Temperature',
  'snHumi': 'Indoor Humidity',
  'snCo2': 'Indoor CO2',
  'snPm25': 'Indoor PM2.5',
  'snTvoc': 'Indoor TVOC',
  'powerOn': 'Power On',
  'powerOff': 'Power Off',
  'mode': 'Mode',
  'auto': 'Auto',
  'cool': 'Cooling',
  'heat': 'Heating',
  'dry': 'Dehumidification',
  'ventilation': 'Ventilation',
  'fanSpeedAdjustment': 'Fan Speed Adjustment',
  'lowWind': 'Low',
  'middlingWind': 'Medium',
  'highWind': 'High',
  'setCo2': 'CO2 Concentration Setting',
  'setHumi': 'Humidity Setting',
  'setHotWater': 'Hot Water Setting',
  'setTime': 'Timer Setting',
  'setFilter': 'Filter Reset',
  'snChart': 'Indoor Parameter Curve Graph',
  'powerUsage': 'Electricity Usage',
  'goToView': 'View',
  'goToSettings': 'Settings',
  'filterTips': 'Pre-filter: XX%, HEPA Filter: YY%',
  'humiTips': 'Can set room relative humidity to maintain stable indoor humidity and avoid over-dehumidification',
  'cxFilter': 'Pre-filter',
  'gxFilter': 'HEPA Filter',
  'resetFilter': 'Reset Filter',
  'resetFilterTips': 'After resetting the filter, the remaining filter time will be recalculated. Do you want to reset?',
  'filterRemaining': 'Filter Remaining',
  'filterTimeTips': 'Estimated Remaining Usage: XX Days',
  'cancel': 'Cancel',
  'sure': 'Confirm',
  'snHumiture': 'Indoor T/H',
  'temp': 'Temperature',
  'humi': 'Humidity',
  'day': 'Day',
  'week': 'Week',
  'month': 'Month',
  'year': 'Yearly',
  'snAirQuality': 'Indoor Air Quality',
  'instantaneous': 'Instantaneous Power',
  'parameterQuery': 'Parameter Query',
  'parameterSettings': 'Professional Parameter Settings',
  'expansion': 'Expansion Valve Opening',
  'compressor': 'Compressor Frequency',
  'snCoilTemp': 'Indoor Coil Temperature',
  'swCoilTemp': 'Outdoor Coil Temperature',
  'dischargeTemp': 'Compressor Discharge Temperature',
  'swAirTemp': 'Outdoor Air Temperature',
  'returnAirTemp': 'Return Air Temperature',
  'addUpElec': 'Cumulative Electricity Consumption',
  'currentUsage': 'Current Electricity Consumption',
  'professional1': 'Supply Fan Speed',
  'professional2': 'Fresh Air Fan Speed',
  'professional3': 'Exhaust Fan Speed',
  'professional4': 'Outdoor Fan Speed',
  'professional5': 'Circulating Air Valve Angle',
  'professional6': 'Temperature Coefficient Correction',
  'professional7': 'Humidity Coefficient Correction',
  'lowSpeed': 'Low Speed',
  'mediumSpeed': 'Medium Speed',
  'highSpeed': 'High Speed',
  'currentValue': 'Current',
  'corrected': 'Corrected',
  'correctionFactor': 'Correction Factor',
  'passwordTips': 'Please Enter Administrator Password',
  'passwordErr': 'Incorrect Password',
  'save': 'Save',
  'hotWaterOff': 'Hot Water Off',
  'hotWaterOn': 'Hot Water On',
  'tempTitle': 'Temperature regulation',
  'currentWaterTemperature': 'Current Water Temperature',
  'hotWaterValve': 'Hot water valve',


  'error1.0': 'Return Air Temperature Sensor Fault Alarm',
  'error1.1': 'Supply Air Temperature Sensor Fault Alarm',
  'error1.2': '--',
  'error1.3': 'Outdoor Ambient Temperature Sensor Fault Alarm',
  'error1.4': 'Outdoor Coil Temperature Sensor Fault Alarm',
  'error1.5': 'Evaporator Coil Temperature Sensor Fault Alarm',
  'error1.6': 'Discharge Temperature Sensor Fault',
  'error1.7': 'Suction Temperature Sensor Fault',
  'error1.8': '--',
  'error1.9': 'Indoor Coil Anti-freeze Protection',
  'error1.10': 'Compressor Discharge Over-temperature Protection',
  'error1.11': 'Water Full Alarm',
  'error1.12': 'Low Refrigerant Protection',
  'error1.13': 'Outdoor Coil High Temperature Protection',
  'error1.14': 'Input Voltage Low Fault',
  'error1.15': '--',

  'error2.0': 'IPM Over/Under Voltage Fault',
  'error2.1': 'IPM Overcurrent Fault',
  'error2.2': 'Indoor/Outdoor Unit Communication Abnormality',
  'error2.3': 'Compressor Fault',
  'error2.4': 'Compressor Fault',
  'error2.5': 'Compressor Fault',
  'error2.6': 'Compressor Fault',
  'error2.7': 'IPM Over-temperature Fault',
  'error2.8': 'Supply Fan 1 Alarm',
  'error2.9': 'Supply Fan 2 Alarm',
  'error2.10': 'Exhaust Fan Alarm',
  'error2.11': 'Fresh Air Fan Alarm',
  'error2.12': 'Outdoor Fan Alarm',
  'error2.13': 'IPM Hardware Fault',
  'error2.14': 'High Voltage Switch Protection',
  'error2.15': 'Low Voltage Switch Protection',

  'error3.0': 'Pre-filter Cleaning Warning',
  'error3.1': 'Medium-efficiency Filter Cleaning Warning',
  'error3.2': 'High-efficiency Filter Cleaning Warning',
  'error3.3': 'Heat Exchanger Core Replacement Warning',
  'error3.4': '--',
  'error3.5': '--',
  'error3.6': '--',
  'error3.7': '--',
  'error3.8': '--',
  'error3.9': '--',
  'error3.10': '--',
  'error3.11': '--',
  'error3.12': '--',
  'error3.13': '--',
  'error3.14': '--',
  'error3.15': 'Communication error between the control panel and the drive board',

  'error4.0': 'Main Screen Communication Abnormality',
  'error4.1': 'Sub-control Screen 1 Communication Abnormality',
  'error4.2': 'Sub-control Screen 2 Communication Abnormality',
  'error4.3': 'Sub-control Screen 3 Communication Abnormality',
  'error4.4': 'Sub-control Screen 4 Communication Abnormality',
  'error4.5': 'Sub-control Screen 5 Communication Abnormality',
  'error4.6': '--',
  'error4.7': '--',
  'error4.8': '--',
  'error4.9': '--',
  'error4.10': '--',
  'error4.11': '--',
  'error4.12': '--',
  'error4.13': '--',
  'error4.14': '--',
  'error4.15': '--',
  'A/SHotline': 'After-sales Service Phone',
  'Iknow': 'I Understand',

  "Mon": "Mon",
  "Tue": "Tue",
  "Wed": "Wed",
  "Thu": "Thu",
  "Fri": "Fri",
  "Sat": "Sat",
  "Sun": "Sun",
  'Close': 'Close',

  'eleTips1': 'Current session consumption: total electricity used since last power-on.',
  'eleTips2': 'Cumulative consumption: total electricity used since factory exit.',

  'rate1': 'EX',
  'rate2': 'GD',
  'rate3': 'LP',
  'rate4': 'MOD P',
  'rate5': 'SP',
  'rate6': 'HZD'
};
